version: '3'

services:

    rabbit:
        image: rabbitmq:3.6.11
        restart: always
        hostname: rabbit
        environment:
            - RABBITMQ_DEFAULT_USER=wiki
            - RABBITMQ_DEFAULT_PASS=wiki123
        ports:
            - "5673:5672"
        volumes:
          - 'wiki_rabbit:/data'

    mongo:
        image: mongo:3.6.2
        restart: always
        hostname: mongo
        ports:
            - 27018:27017
        volumes:
            - 'wiki_mongo:/data/db'

    nginx:
        hostname: nginx
        image: nginx:1.13.11-alpine
        restart: always
        links:
            - flask
            - flower:flower
        ports:
            - "80:80"
        volumes:
            - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
            - './docker/nginx/.htpasswd:/etc/nginx/.htpasswd'

    flask:
        build: .
        image: wheapi
        restart: always
        environment:
            - FLASK_CONFIG=docker
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - MONGO_USERNAME=wiki
            - MONGO_PASSWORD=wiki123
            - MONGO_DB_NAME=wiki_history_extractor
            - MONGO_DB_TEST_NAME=wiki_history_extractor_test
            - CELERY_BROKER_URL=amqp://wiki:wiki123@rabbit:5672
            - CELERY_RESULT_BACKEND=amqp://wiki:wiki123@rabbit:5672
            - FLASK_DEBUG=1
        # command: python manage.py runserver --host 0.0.0.0 --port=3031
        command: /usr/local/bin/uwsgi --socket 0.0.0.0:3031 --uid uwsgi --protocol uwsgi --wsgi manage:app --py-autoreload 1
        # command: /usr/local/bin/uwsgi --socket 0.0.0.0:3031 --uid uwsgi --protocol http --wsgi manage:app --py-autoreload 1
        links:
            - rabbit
            - mongo:mongo
        ports:
            - "3031:3031"
        volumes:
          - '.:/app'
        depends_on:
            - rabbit
            - mongo

    worker:
        image: wheapi
        restart: always
        command: celery worker -A celery_worker.celery --loglevel=info
        environment:
            - FLASK_CONFIG=docker
            - PYTHONBUFFERED=true
            - FLASK_DEBUG=1
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - MONGO_USERNAME=wiki
            - MONGO_PASSWORD=wiki123
            - MONGO_DB_NAME=wiki_history_extractor
            - MONGO_DB_TEST_NAME=wiki_history_extractor_test
            - CELERY_BROKER_URL=amqp://wiki:wiki123@rabbit:5672
            - CELERY_RESULT_BACKEND=amqp://wiki:wiki123@rabbit:5672
        links:
            - rabbit
            - mongo:mongo
        depends_on:
            - rabbit
            - mongo

    flower:
        hostname: flower
        image: wheapi
        restart: always
        command: flower -A celery_worker.celery --loglevel=info --broker=amqp://wiki:wiki123@rabbit:5672 --url_prefix=flower
        ports:
            - "5555:5555"
        links:
            - rabbit
        depends_on:
            - rabbit

    adminmongo:
        hostname: adminmongo
        image: mrvautin/adminmongo
        links:
            - mongo:mongo
        ports:
            - 1234:1234
        environment:
            - HOST=0.0.0.0
            - CONN_NAME=wiki
            - DB_USERNAME=wiki
            - DB_PASSWORD=wiki123
            - DB_HOST=mongo
            - DB_PORT=27017
            - DB_NAME=wiki_history_extractor
            - PASSWORD=wiki123
            - CONTEXT=adminmongo
        volumes:
            - './docker/adminmongo/app.json:/app/user/config/app.json'

volumes:
    wiki_rabbit:
    wiki_mongo:
